# 头部菜单，title: link
menu:
  Github: https://github.com/list17
  Pornhub: http://www.shdf.gov.cn/
  归档: /archives
  标签云: /tags

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - http://link.hhtjim.com/163/5146554.mp3
  - http://link.hhtjim.com/qq/001faIUs4M2zna.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: /img/write-blog-tools.jpeg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: f4050047fc1d032dbe41
    # 应用秘钥
    clientSecret: 1a7a3a00676e4fef3992526b5c60a7c3e6fc7e91
    # issue仓库名
    repo: list-blog
    # Github名
    owner: list17
    # Github名
    admin: "list17"
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: List

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
